CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMER (
    CUSTID VARCHAR(50),
    NAME VARCHAR(255),
    EMAILID VARCHAR(255),
    REGION VARCHAR(100),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC."order" (
    ORDERID VARCHAR(50),
    CUSTID VARCHAR(50),
    ITEMNAME VARCHAR(255),
    PRICEPERUNIT NUMBER(18,2),
    QTY NUMBER(18,0),
    ORDER_DATE DATE,
    STARTDATE DATE,
    ENDDATE DATE,
    ISACTIVE VARCHAR(10),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);