BEGIN
    CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.RAW_CUSTOMER (
        CUSTID VARCHAR(100),
        NAME VARCHAR(255),
        EMAILID VARCHAR(255),
        REGION VARCHAR(100)
    );

    CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.RAW_ORDER (
        ORDERID VARCHAR(100),
        ITEMNAME VARCHAR(255),
        PRICEPERUNIT VARCHAR(50),
        QTY VARCHAR(50),
        DATE VARCHAR(50),
        CUSTID VARCHAR(100)
    );

    CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CLEAN_CUSTOMER (
        CUSTID VARCHAR(100),
        NAME VARCHAR(255),
        EMAILID VARCHAR(255),
        REGION VARCHAR(100)
    );

    CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CLEAN_ORDER (
        ORDERID VARCHAR(100),
        ITEMNAME VARCHAR(255),
        PRICEPERUNIT NUMBER(18,2),
        QTY NUMBER(18,0),
        DATE DATE,
        CUSTID VARCHAR(100)
    );

    CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ORDERSUMMARY (
        CUSTID VARCHAR(100),
        NAME VARCHAR(255),
        EMAILID VARCHAR(255),
        REGION VARCHAR(100),
        ORDERID VARCHAR(100),
        ITEMNAME VARCHAR(255),
        PRICEPERUNIT NUMBER(18,2),
        QTY NUMBER(18,0),
        DATE DATE,
        STARTDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        ENDDATE TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ,
        ISACTIVE BOOLEAN DEFAULT TRUE
    );

    CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMERAGGREGATESPEND (
        NAME VARCHAR(255),
        DATE DATE,
        TOTALAMOUNT NUMBER(18,2)
    );

    RETURN 'All tables created successfully';
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;