BEGIN
    TRUNCATE TABLE IF EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.RAW_CUSTOMER;

    COPY INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.RAW_CUSTOMER
    FROM @gen_ai_poc_snowflakecoe.sdlc_wizard.sdlc_wizard_stage/customerdata
    FILE_FORMAT = (
        TYPE = 'CSV'
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    )
    ON_ERROR = CONTINUE;

    TRUNCATE TABLE IF EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.RAW_ORDER;

    COPY INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.RAW_ORDER
    FROM @gen_ai_poc_snowflakecoe.sdlc_wizard.sdlc_wizard_stage/orderdata
    FILE_FORMAT = (
        TYPE = 'CSV'
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    )
    ON_ERROR = CONTINUE;

    RETURN 'Raw data loaded successfully';
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;