CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_DATA_QUALITY_CLEANSING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    -- Cleanse customer data: remove 'Null' strings, actual NULLs, and duplicates
    TRUNCATE TABLE IF EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CLEAN_CUSTOMER;

    INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CLEAN_CUSTOMER (CUSTID, NAME, EMAILID, REGION)
    SELECT
        CUSTID,
        NAME,
        EMAILID,
        REGION
    FROM (
        SELECT
            CASE WHEN UPPER(TRIM(CUSTID)) = 'NULL' OR CUSTID IS NULL THEN NULL ELSE TRIM(CUSTID) END AS CUSTID,
            CASE WHEN UPPER(TRIM(NAME)) = 'NULL' OR NAME IS NULL THEN NULL ELSE TRIM(NAME) END AS NAME,
            CASE WHEN UPPER(TRIM(EMAILID)) = 'NULL' OR EMAILID IS NULL THEN NULL ELSE TRIM(EMAILID) END AS EMAILID,
            CASE WHEN UPPER(TRIM(REGION)) = 'NULL' OR REGION IS NULL THEN NULL ELSE TRIM(REGION) END AS REGION,
            ROW_NUMBER() OVER (PARTITION BY TRIM(CUSTID) ORDER BY TRIM(NAME)) AS RN
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.RAW_CUSTOMER
        WHERE CUSTID IS NOT NULL
          AND UPPER(TRIM(CUSTID)) != 'NULL'
          AND TRIM(CUSTID) != ''
    )
    WHERE RN = 1
      AND CUSTID IS NOT NULL;

    -- Cleanse order data: remove 'Null' strings, actual NULLs, and duplicates
    TRUNCATE TABLE IF EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CLEAN_ORDER;

    INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CLEAN_ORDER (ORDERID, ITEMNAME, PRICEPERUNIT, QTY, DATE, CUSTID)
    SELECT
        ORDERID,
        ITEMNAME,
        PRICEPERUNIT,
        QTY,
        DATE,
        CUSTID
    FROM (
        SELECT
            CASE WHEN UPPER(TRIM(ORDERID)) = 'NULL' OR ORDERID IS NULL THEN NULL ELSE TRIM(ORDERID) END AS ORDERID,
            CASE WHEN UPPER(TRIM(ITEMNAME)) = 'NULL' OR ITEMNAME IS NULL THEN NULL ELSE TRIM(ITEMNAME) END AS ITEMNAME,
            CASE WHEN UPPER(TRIM(PRICEPERUNIT)) = 'NULL' OR PRICEPERUNIT IS NULL THEN NULL ELSE TRY_CAST(TRIM(PRICEPERUNIT) AS NUMBER(18,2)) END AS PRICEPERUNIT,
            CASE WHEN UPPER(TRIM(QTY)) = 'NULL' OR QTY IS NULL THEN NULL ELSE TRY_CAST(TRIM(QTY) AS NUMBER(18,0)) END AS QTY,
            CASE WHEN UPPER(TRIM(DATE)) = 'NULL' OR DATE IS NULL THEN NULL ELSE TRY_CAST(TRIM(DATE) AS DATE) END AS DATE,
            CASE WHEN UPPER(TRIM(CUSTID)) = 'NULL' OR CUSTID IS NULL THEN NULL ELSE TRIM(CUSTID) END AS CUSTID,
            ROW_NUMBER() OVER (PARTITION BY TRIM(ORDERID) ORDER BY TRIM(ITEMNAME)) AS RN
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.RAW_ORDER
        WHERE ORDERID IS NOT NULL
          AND UPPER(TRIM(ORDERID)) != 'NULL'
          AND TRIM(ORDERID) != ''
    )
    WHERE RN = 1
      AND ORDERID IS NOT NULL
      AND PRICEPERUNIT IS NOT NULL
      AND QTY IS NOT NULL
      AND DATE IS NOT NULL
      AND CUSTID IS NOT NULL;

    RETURN 'Data quality cleansing completed successfully';
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;
$$;