BEGIN
    CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ORDERSUMMARY (
        CUSTID VARCHAR(100),
        NAME VARCHAR(255),
        EMAILID VARCHAR(255),
        REGION VARCHAR(100),
        ORDERID VARCHAR(100),
        ITEMNAME VARCHAR(255),
        PRICEPERUNIT NUMBER(18,2),
        QTY NUMBER(18,0),
        DATE DATE,
        STARTDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        ENDDATE TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ,
        ISACTIVE BOOLEAN DEFAULT TRUE
    );

    RETURN 'ORDERSUMMARY SCD2 table verified/created successfully';
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;