-- Remove null records from customer table (where key fields are null)
DELETE FROM IDEA_2_DB.PUBLIC.CUSTOMER
WHERE CUSTID IS NULL
   OR NAME IS NULL
   OR EMAILID IS NULL;

-- Remove duplicate records from customer table, keeping the latest loaded record
DELETE FROM IDEA_2_DB.PUBLIC.CUSTOMER
WHERE CTID IN (
    SELECT CTID FROM (
        SELECT
            CUSTID,
            LOAD_TIMESTAMP,
            ROW_NUMBER() OVER (PARTITION BY CUSTID ORDER BY LOAD_TIMESTAMP DESC) AS RN
        FROM IDEA_2_DB.PUBLIC.CUSTOMER
    )
    WHERE RN > 1
);

-- Alternative approach using a temp table for deduplication
CREATE OR REPLACE TEMPORARY TABLE IDEA_2_DB.PUBLIC.CUSTOMER_CLEAN AS
SELECT *
FROM IDEA_2_DB.PUBLIC.CUSTOMER
QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTID ORDER BY LOAD_TIMESTAMP DESC) = 1;

TRUNCATE TABLE IDEA_2_DB.PUBLIC.CUSTOMER;

INSERT INTO IDEA_2_DB.PUBLIC.CUSTOMER
SELECT * FROM IDEA_2_DB.PUBLIC.CUSTOMER_CLEAN;