CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_CUSTOMER_AGGREGATE_SPEND()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    -- Truncate and reload aggregate spend table
    TRUNCATE TABLE IF EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMERAGGREGATESPEND;

    INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMERAGGREGATESPEND (NAME, DATE, TOTALAMOUNT)
    SELECT
        NAME,
        DATE,
        SUM(PRICEPERUNIT * QTY) AS TOTALAMOUNT
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ORDERSUMMARY
    WHERE ISACTIVE = TRUE
    GROUP BY NAME, DATE
    ORDER BY NAME, DATE;

    RETURN 'Customer aggregate spend calculated successfully';
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;
$$;