-- Remove null records from order table (where key fields are null)
DELETE FROM IDEA_2_DB.PUBLIC."order"
WHERE ORDERID IS NULL
   OR CUSTID IS NULL
   OR ITEMNAME IS NULL
   OR PRICEPERUNIT IS NULL
   OR QTY IS NULL;

-- Remove duplicate records from order table, keeping the latest loaded record
CREATE OR REPLACE TEMPORARY TABLE IDEA_2_DB.PUBLIC.ORDER_CLEAN AS
SELECT *
FROM IDEA_2_DB.PUBLIC."order"
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDERID ORDER BY LOAD_TIMESTAMP DESC) = 1;

TRUNCATE TABLE IDEA_2_DB.PUBLIC."order";

INSERT INTO IDEA_2_DB.PUBLIC."order"
SELECT * FROM IDEA_2_DB.PUBLIC.ORDER_CLEAN;