CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_EXECUTE_SCD2_PIPELINE()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_RESULT_LOAD VARCHAR;
    V_RESULT_CLEANSE VARCHAR;
    V_RESULT_SCD2 VARCHAR;
    V_RESULT_AGGREGATE VARCHAR;
BEGIN
    -- Step 1: Load raw data from stage
    TRUNCATE TABLE IF EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.RAW_CUSTOMER;

    COPY INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.RAW_CUSTOMER
    FROM @gen_ai_poc_snowflakecoe.sdlc_wizard.sdlc_wizard_stage/customerdata
    FILE_FORMAT = (
        TYPE = 'CSV'
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    )
    ON_ERROR = CONTINUE;

    TRUNCATE TABLE IF EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.RAW_ORDER;

    COPY INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.RAW_ORDER
    FROM @gen_ai_poc_snowflakecoe.sdlc_wizard.sdlc_wizard_stage/orderdata
    FILE_FORMAT = (
        TYPE = 'CSV'
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    )
    ON_ERROR = CONTINUE;

    -- Step 2: Data quality cleansing
    CALL GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_DATA_QUALITY_CLEANSING() INTO :V_RESULT_CLEANSE;

    IF (V_RESULT_CLEANSE LIKE '%error%') THEN
        RETURN V_RESULT_CLEANSE;
    END IF;

    -- Step 3: SCD Type 2 merge
    CALL GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_SCD2_ORDERSUMMARY() INTO :V_RESULT_SCD2;

    IF (V_RESULT_SCD2 LIKE '%error%') THEN
        RETURN V_RESULT_SCD2;
    END IF;

    -- Step 4: Customer aggregate spend
    CALL GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_CUSTOMER_AGGREGATE_SPEND() INTO :V_RESULT_AGGREGATE;

    IF (V_RESULT_AGGREGATE LIKE '%error%') THEN
        RETURN V_RESULT_AGGREGATE;
    END IF;

    RETURN OBJECT_CONSTRUCT(
        'status', 'SUCCESS',
        'message', 'SCD2 pipeline executed successfully',
        'step1_load', 'Completed',
        'step2_cleanse', V_RESULT_CLEANSE,
        'step3_scd2', V_RESULT_SCD2,
        'step4_aggregate', V_RESULT_AGGREGATE
    )::VARCHAR;

EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;
$$;