-- Step 1: Create a staging view with joined customer and order data
CREATE OR REPLACE TEMPORARY TABLE IDEA_2_DB.PUBLIC.ORDERSUMMARY_STG AS
SELECT
    O.ORDERID,
    C.CUSTID,
    C.NAME,
    C.EMAILID,
    C.REGION,
    O.ITEMNAME,
    O.PRICEPERUNIT,
    O.QTY,
    (O.PRICEPERUNIT * O.QTY) AS TOTALAMOUNT,
    O.ORDER_DATE,
    O.STARTDATE,
    O.ENDDATE,
    O.ISACTIVE
FROM IDEA_2_DB.PUBLIC."order" O
INNER JOIN IDEA_2_DB.PUBLIC.CUSTOMER C
    ON O.CUSTID = C.CUSTID;

-- Step 2: Expire existing records where customer data has changed (SCD Type 2)
UPDATE IDEA_2_DB.PUBLIC.ORDERSUMMARY TGT
SET
    IS_CURRENT = FALSE,
    EFFECTIVE_TO = CURRENT_TIMESTAMP()
WHERE TGT.IS_CURRENT = TRUE
  AND EXISTS (
      SELECT 1
      FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY_STG STG
      WHERE STG.ORDERID = TGT.ORDERID
        AND STG.CUSTID = TGT.CUSTID
        AND (
            STG.NAME != TGT.NAME
            OR STG.EMAILID != TGT.EMAILID
            OR STG.REGION != TGT.REGION
            OR STG.ITEMNAME != TGT.ITEMNAME
            OR STG.PRICEPERUNIT != TGT.PRICEPERUNIT
            OR STG.QTY != TGT.QTY
        )
  );

-- Step 3: Insert new versions of changed records
INSERT INTO IDEA_2_DB.PUBLIC.ORDERSUMMARY (
    ORDERID, CUSTID, NAME, EMAILID, REGION, ITEMNAME,
    PRICEPERUNIT, QTY, TOTALAMOUNT, ORDER_DATE, STARTDATE, ENDDATE,
    ISACTIVE, IS_CURRENT, EFFECTIVE_FROM, EFFECTIVE_TO, LOAD_TIMESTAMP
)
SELECT
    STG.ORDERID,
    STG.CUSTID,
    STG.NAME,
    STG.EMAILID,
    STG.REGION,
    STG.ITEMNAME,
    STG.PRICEPERUNIT,
    STG.QTY,
    STG.TOTALAMOUNT,
    STG.ORDER_DATE,
    STG.STARTDATE,
    STG.ENDDATE,
    STG.ISACTIVE,
    TRUE,
    CURRENT_TIMESTAMP(),
    '9999-12-31 00:00:00',
    CURRENT_TIMESTAMP()
FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY_STG STG
WHERE EXISTS (
    SELECT 1
    FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY TGT
    WHERE TGT.ORDERID = STG.ORDERID
      AND TGT.CUSTID = STG.CUSTID
      AND TGT.IS_CURRENT = FALSE
      AND TGT.EFFECTIVE_TO = (
          SELECT MAX(EFFECTIVE_TO)
          FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY
          WHERE ORDERID = STG.ORDERID AND CUSTID = STG.CUSTID
      )
      AND (
          STG.NAME != TGT.NAME
          OR STG.EMAILID != TGT.EMAILID
          OR STG.REGION != TGT.REGION
          OR STG.ITEMNAME != TGT.ITEMNAME
          OR STG.PRICEPERUNIT != TGT.PRICEPERUNIT
          OR STG.QTY != TGT.QTY
      )
);

-- Step 4: Insert brand new records that don't exist in target
INSERT INTO IDEA_2_DB.PUBLIC.ORDERSUMMARY (
    ORDERID, CUSTID, NAME, EMAILID, REGION, ITEMNAME,
    PRICEPERUNIT, QTY, TOTALAMOUNT, ORDER_DATE, STARTDATE, ENDDATE,
    ISACTIVE, IS_CURRENT, EFFECTIVE_FROM, EFFECTIVE_TO, LOAD_TIMESTAMP
)
SELECT
    STG.ORDERID,
    STG.CUSTID,
    STG.NAME,
    STG.EMAILID,
    STG.REGION,
    STG.ITEMNAME,
    STG.PRICEPERUNIT,
    STG.QTY,
    STG.TOTALAMOUNT,
    STG.ORDER_DATE,
    STG.STARTDATE,
    STG.ENDDATE,
    STG.ISACTIVE,
    TRUE,
    CURRENT_TIMESTAMP(),
    '9999-12-31 00:00:00',
    CURRENT_TIMESTAMP()
FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY_STG STG
WHERE NOT EXISTS (
    SELECT 1
    FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY TGT
    WHERE TGT.ORDERID = STG.ORDERID
      AND TGT.CUSTID = STG.CUSTID
);