CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND (
    NAME VARCHAR(255),
    ORDER_DATE DATE,
    TOTAL_SPEND NUMBER(18,2),
    RECORD_COUNT NUMBER(18,0),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);