-- Truncate and reload aggregated spend data
TRUNCATE TABLE IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND;

INSERT INTO IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND (NAME, ORDER_DATE, TOTAL_SPEND, RECORD_COUNT, LOAD_TIMESTAMP)
SELECT
    NAME,
    ORDER_DATE,
    SUM(TOTALAMOUNT) AS TOTAL_SPEND,
    COUNT(*) AS RECORD_COUNT,
    CURRENT_TIMESTAMP()
FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY
WHERE IS_CURRENT = TRUE
GROUP BY NAME, ORDER_DATE
ORDER BY NAME, ORDER_DATE;