CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.ERROR_LOG (
    ERROR_ID NUMBER AUTOINCREMENT,
    PROCEDURE_NAME VARCHAR(255),
    ERROR_MESSAGE VARCHAR(4000),
    ERROR_STATE VARCHAR(50),
    ERROR_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);